### ISSUE TITLE
Data generation with schema

### ISSUE THREAD

**Issue by giorgio-v** [Prismatic/schema#103]
In the readme you said that you want to provide the ability to generate data from a given schema. 

Since I will need a feature like this in the near future I’d like to know if this is still a planned feature and, if so, whether or not you’d like to discuss its design here. 

I’m willing to contribute some effort and spare time to implement this.

TIA

**Comment by w01fe** [comment]
1.0.0 includes experimental generation support, would love your feedback on that!  Please open a new issue if it doesn't meet your needs.
