### ISSUE TITLE
issues due to defaulting to using potemkin/defrecord+

### ISSUE THREAD

**Issue by tanzoniteblack** [Prismatic/schema#112]
schema.macro/*use-potemkin* defaults to true, which can cause unexpected issues while developing if the project doesn't also use potemkin.

If a record implements a protocol defined using clojure's built in `defprotocol`, then when you evaluate a `schema/defrecord` a second time, the protocol that the record implements is overridden, but the record isn't re-implemented. This causes the record to not implement the protocol that it did before.

Example code:
```clojure
(ns user-test
  (:require [schema.core :as schema]
            [potemkin]))

(potemkin/defprotocol+ TestProtocol1
  (print-me1 [this]))

(defprotocol TestProtocol2
  (print-me2 [this]))

(schema/defrecord TestRecord1
    [cat :- schema/Str]
  TestProtocol1
  (print-me1 [this] (println this))
  TestProtocol2
  (print-me2 [this] (println this)))

(potemkin/defrecord+ TestRecord2
  [cat]
  TestProtocol1
  (print-me1 [this] (println this))
  TestProtocol2
  (print-me2 [this] (println this)))

(defrecord TestRecord3
    [cat]
  TestProtocol1
  (print-me1 [this] (println this))
  TestProtocol2
  (print-me2 [this] (println this)))

(defn use-test-record []
  (doseq [f [map->TestRecord1 map->TestRecord2 map->TestRecord3]]
    (try (print-me1 (f {:cat "cat"}))
         (catch Throwable e
           (println (.getMessage e))))
    (try (print-me2 (f {:cat "cat"}))
         (catch Throwable e
           (println (.getMessage e))))))
```

The first time the code is evaluated, and `(use-test-record)` is run, it prints out what you'd expect:
```
#user_test.TestRecord1{:cat cat}
#user_test.TestRecord1{:cat cat}
#user_test.TestRecord2{:cat cat}
#user_test.TestRecord2{:cat cat}
#user_test.TestRecord3{:cat cat}
#user_test.TestRecord3{:cat cat}
nil
```

If you evaluate the code again, and attempt to run `(use-test-record)` it throws errors:
```
#user_test.TestRecord1{:cat cat}
No implementation of method: :print-me2 of protocol: #'user-test/TestProtocol2 found for class: user_test.TestRecord1
#user_test.TestRecord2{:cat cat}
No implementation of method: :print-me2 of protocol: #'user-test/TestProtocol2 found for class: user_test.TestRecord2
#user_test.TestRecord3{:cat cat}
#user_test.TestRecord3{:cat cat}
```

Running `(reset! schema.macros/*use-potemkin* false)` allows all of the records created through schema to work correctly, so if using potemkin is the desired default, then you should at least put a warning in the documentation about the dangers of not turning off this variable if you don't use potemkin in your package.

**Comment by expez** [comment]
Anything happening with this?

i just had to add a `:exclusion` because of potemkin conflicts.

**Comment by w01fe** [comment]
Haven't had a chance to get to this yet, but will aim to get it out soon.
