### ISSUE TITLE
Custom error messages with s/conditional

### ISSUE THREAD

**Issue by lvh** [Prismatic/schema#141]
As with s/pred, I'd like to have a custom error message for `s/conditional` to clarify *why* a schema didn't parse. The default message, `(not (matches-some-condition? a-clojure.lang.PersistentHashMap))`, is accurate, but not something optimal for passing it back to users.

I came up with this way of doing it, but I don't know if that's idiomatic, or if there even is an idiomatic way of doing it:

```clojure
:else (s/pred (constantly false) "should've been one of the previous cases")
```

Is this a bad idea? Am I missing something?

There's really only one thing (and that may be because I'm `pr-str` ing the ValidationErrors):

```
(not ("supported-step-type" a-clojure.lang.PersistentHashMap))
```

It'd be nice if `a-clojure.lang.PersistentHashMap` was a representation of the map, or `(:type that-map)`.

Thanks again for all the hard work on schema. Sorry for the silly questions :)

**Comment by w01fe** [comment]
As of 1.0.0 `s/conditional` now supports a final argument that supplies the error message (or if there's a single option, infers a name from the corresponding predicate.)  Please reopen if this doesn't meet your needs.  Thanks!
