### ISSUE TITLE
Cross-platform atomic value schema do not add :tag type-hint

### ISSUE THREAD

**Issue by mrrodriguez** [Prismatic/schema#174]
The cross-platform schema provided in schema.core do not add :tag type-hints that I'd expect.

I think a few examples is the best way to demonstrate:
```clj
;;; Using cross-platform schema on fn return
(schema.core/defn ret-str :- schema.core/Str
   []
  "abc")

(:tag (meta #'ret-str)) ;= nil

;; Using actual class symbol on fn return
(schema.core/defn ret-str :- java.lang.String
  []
  "abc")

(:tag (meta #'ret-str)) ;= java.lang.String

;; Using cross-platform schema on fn arg
(schema.core/defn take-str [x :- schema.core/Str]
  x)

(meta (first (first (:arglists (meta #'take-str))))) ;= {:schema schema.core/Str}

;; Using actual class symbol on fn arg
(schema.core/defn take-str [x :- java.lang.String]
  x)

(meta (first (first (:arglists (meta #'take-str))))) ;= {:schema java.lang.String, :tag java.lang.String}
```

I looked briefly into why this may be the case, I think the issue comes from the 
`schema.macros/valid-tag?` function around
https://github.com/Prismatic/schema/blob/master/src/clj/schema/macros.clj#L100 .

I traced this back from the `schema.core/defn` (that currently only passes through to `schema.macros/defn`).

This example demonstrates where the difference in :tag type-hinting behavior occurs:
```clj
(schema.macros/valid-tag? {} 'schema.core/Str) ;= false

(schema.macros/valid-tag? {} 'java.lang.String) ;= true
```

Specifically the part of `valid-tag?`that attempts to resolve the given symbol to a `class?`, which looks like:
```clj
(class? (resolve env tag))
```

I do have a potential fix for this issue, but I'm not sure it is the most "elegant" approach to solving the problem.
This can be seen on a branch of my forked repo @ https://github.com/mrrodriguez/schema/compare/cross-platform-schema-type-hints right now.

I can make a pull request for my proposed changes if they end up looking good to you.

Thanks.

**Comment by kgann** [comment]
@w01fe Would you still be open to a PR for this issue? We have a lot of cross-platform libraries and are on a mission to remove as much reflection as possible.

**Comment by w01fe** [comment]
Sure, open to a PR.  Thanks!
