### ISSUE TITLE
Should nil pass validation when expecting a [ ] ?

### ISSUE THREAD

**Issue by omartell** [Prismatic/schema#175]
Hello,

I was trying to validate a couple of non empty sequences and was wondering if this is actually expected behaviour:

```clojure
user => (s/check [] nil)
;; => nil

user => (s/check [String] nil)
;; => nil
```

I had to resort to the following to a valid a non empty sequence of strings:

```clojure

user => (s/check [(s/one String "Url") String] nil)
;; => [(not (present? "Url"))]
```

And I couldn't find a way to validate a sequence with zero or more strings without accepting nil.

Thanks for an awesome library.

**Comment by w01fe** [comment]
Thanks for the kind words.  

Schema's built-in sequence validators accept any sequence, and `nil` is a valid (empty) sequence in Clojure.  

If you want to check for a non-empty sequence or a specific sequence type, the simplest solution is to use `both`: e.g. `(s/both [String] (s/pred seq))` or, for your second example,  `(s/both [String] (s/pred vector?))`.

HTH!
