### ISSUE TITLE
JSON UUID coercion

### ISSUE THREAD

**Issue by yhmtg** [Prismatic/schema#178]
It would be great if the json-coercion-matcher would convert UUID-String automatically into real Java-UUIDs.

I've got it to work this way:
```
(defn json-coercion-matcher-with-UUIDs
  [schema]
  (or ({schema.core/Uuid (schema.coerce/safe (fn [x] (java.util.UUID/fromString x)))} schema)
      (schema.coerce/json-coercion-matcher schema)))
```

**Comment by w01fe** [comment]
Sounds reasonable to me -- pull request welcome!

**Comment by loganlinn** [comment]
@yhmtg Give `[prismatic/schema "0.3.7"]` a try

**Comment by yhmtg** [comment]
Works fine. Any chance we can get in coercion for dates too (see code below)?

```
(def num-or-string->date
  #+clj
  #(try (javax.xml.bind.DatatypeConverter/parseDateTime %) ; ISO date format
     (catch Exception e1
       (try (java.util.Date. (Long. %)) ; Epoch format
         (catch Exception e2 %))))
  #+cljs
  #(let [d (js/Date. %)]
     (if (js/isNaN (.getTime d)) % d)))
```

**Comment by w01fe** [comment]
Hmmm -- Thanks, but honestly, my inclination is to stay as far away from
dates as I can.  There are many potential ways to potentially convert json
into a Date, and while the ones you provide seem to be the right ones, that
doesn't mean everyone is using them, so for now let's keep them outside the
core library.  (Coercions were built to be easily extensible, so you
shouldn't need it in core for it to be useful for you, and at Prismatic
internally we use lots of coercions that we don't feel belong in core).
Thanks!
