### ISSUE TITLE
integrating Datascript: should a value really conform "map?" inside CLJS map-walker?

### ISSUE THREAD

**Issue by nahuel** [Prismatic/schema#181]
I'm trying to validate Datascript entities using Prismatic Schema. Try the following:

```clojure
(ns xxx
   (:require
    [datascript  :as data]
    [schema.core :as s :include-macros true]))

(s/defschema S {:db/id s/Int
                :name  s/Str})

(def db (data/create-conn {}))
(data/transact! db [{ :db/id -1
                      :name "Rulo"}
                    { :db/id -2
                      :color :red}])
(def e  (data/entity @db 1))
(def e2 (data/entity @db 2))

(println "(type e):" (type e))  
(println "Check: " (s/check S e))
(let [old-map? map?]    
  (with-redefs [map? #(if (= (type %) datascript.impl.entity/Entity)
                        true
                        (old-map? %))]
    (println "redef Check 1: " (s/check S e)) 
    (println "redef Check 2: " (s/check S e2)) 
    ))
```
Output: 

```
(type e): datascript.impl.entity/Entity
Check: (not (map? {:db/id 1}))
redef Check 1: nil
redef Check 2: {:name missing-required-key, :color disallowed-key}
```

Datascript entities are defined with `deftype` , so `(map? e)` will return `false` for them, but anyway they implement a good chunk of the map interface, at least the sufficient to validate against a map schema without problems when changing only the `map?` definition (see https://github.com/tonsky/datascript/blob/master/src/datascript/impl/entity.cljs#L65 ) . DS Entities can't be proper maps because you can't `assoc` or `dissoc` on them (they are "changed" only using DS transactions), but Prismatic Schema doesn't need to `assoc` or `dissoc` anything to validate them. 

Now I see two possible ways (besides the previous `map?` redef hack) without changing `schema.core` to really support them:

1-  `(extend-protocol cljs.core/IMap datascript.impl.entity/Entity)` so `(map? e)` always return `true`, but this is impracticable because it will break code (as said before, entities can't be completely proper maps). 

2- `(extend-protocol Schema ....)` in a very similar way as is done here for Records: https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx#L868 . The problem is `schema.core/map-walker` only can be reused if is enclosed with another with `map?` redef hack, seems fragile. And not reusing it will mean duplicate a lot of `schema.core` code. 

But the point is I'm not sure if `schema.core` is doing the right thing when checking the value `map?`, at least in the CLJS case (because of that I'm posting this as an schema issue). This is the CLJS `map?` source:

```clojure
(defprotocol IMap
  #_(-assoc-ex [coll k v])
  (^clj -dissoc [coll k]))

;; ....

(defn ^boolean map?
  "Return true if x satisfies IMap"
  [x]
  (if (nil? x)
    false
    (satisfies? IMap x)))
```

So it seems a little weird `map-walker` in his CLJS version is checking for values with a `-dissoc` operation but it never calls `dissoc` on them. Note, the CLJ/JVM `map?` version checks for `clojure.lang.IPersistentMap`, a different beast than `cljs.core/IMap`. So maybe we need to change `schema.core` in one of the following ways:

3- Change `map-walker` in the CLJS case to use `(satisfies? ILookup x)` instead of `(map? e)` or something like that, specifying the real interface it needs to use.

4- Add a `(defprotocol IMapLikeValue)` to `schema.core` and change in `map-walker` the `(map? x)` call for `(or (map? x) (satisfies? IMapLikeValue x))` so later in user code you can do `(extend-protocol schema.core/IMapLikeValue datascript.impl.entity/Entity)`. 

What do you think?

**Comment by w01fe** [comment]
Thanks for the report. 

I don't know much about datascript, but I think if entities aren't maps, then map schemas are performing as advertised.  It also doesn't seem like map-walker is fully appropriate here, because for coercion and such, we have to be able to reconstruct the entity, not just tear it apart.  If we do what you describe, you'll end up with normal maps back after walking, not entities as you expect.  

Because Entities aren't Maps, I don't think (1) seems like a good idea.  

I think (2) can be done with no schema changes, if you're willing to convert your entity to a map with `(into {})` before calling the map-walker -- this seems like a reasonable option to me, would that work for you?

**Comment by nahuel** [comment]
A coercing scenario was something outside my sight. I will take your suggestion and convert recursively the entity to a proper map before passing it to `map-walker`, can live with that little overhead. Thanks for your reply.

**Comment by w01fe** [comment]
Sounds good.  FWIW, you shouldn't have to recursively convert -- if your
Entity schema converts at one level, the recursion should be handled by the
schema walking.
