### ISSUE TITLE
Does pred work?

### ISSUE THREAD

**Issue by mhluongo** [Prismatic/schema#182]
In 0.3.0 this works as expected

```clojure
> (s/check (s/pred #(= :test %)) :not-test)
(not (#<handler$eval3196$fn__3197 shale.handler$eval3196$fn__3197@52e14f48> :not-test))
```

but after upgrading to 0.3.7 I get
```clojure
> (s/check (s/pred #(= :test %)) :not-test)
nil
```

**Comment by w01fe** [comment]
Thanks for the report.  That works fine for me.  What language (cljs or
cljs) and version?  Looks like your parens are mismatched as well, FWIW.

**Comment by mhluongo** [comment]
Sorry, fixed the parens- I had edited the actual example of the issue from [another project](https://github.com/cardforcoin/shale).

I just tried it again. Plain clj, version 1.6.0. The entire lein repl session is
```clojure
shale.handler=> (require '[schema.core :as s])
nil
shale.handler=> (s/check (s/pred #(= :test %)) :not-test)
nil
```

**Comment by mhluongo** [comment]
Tried 0.3.1-0.3.6. It works as expected in 0.3.1 as well, then the rest show the above behavior.

**Comment by w01fe** [comment]
Very strange.  I see:

```clojure
; CIDER 0.5.0 (Clojure 1.6.0, nREPL 0.2.3)
user> (require '[schema.core :as s])
nil
user>  (s/check (s/pred #(= :test %)) :not-test)
(not (#<user$eval9977$fn__9978 user$eval9977$fn__9978@15d61781> :not-test))
```

Seems like this might be due to interactions of some sort with other dependencies or project options -- any chance you can provide a minimal test project?  Much appreciated.

**Comment by w01fe** [comment]
Closing for now, if you can provide a reduced test case please reopen and we will look into it further.  Thanks!
