### ISSUE TITLE
compilation of cljs fails 

### ISSUE THREAD

**Issue by jessitron** [Prismatic/schema#184]
"lein test" fails for me (lein 2.5.0), on both the tip of master and the 0.3.7 release commit.
It throws this exception in the ClojureScript compile:

```
Compiling "target/unit-test-no-assert.js" from ["src/clj" "test/clj" "target/generated/src/cljs" "target/generated/test/cljs"]...
Compiling "target/unit-test-no-assert.js" failed.
clojure.lang.ExceptionInfo:  at line 1  {:tag :cljs/analysis-error, :file nil, :line 1, :column 1}
	at clojure.core$ex_info.invoke(core.clj:4327)
...
Caused by: java.lang.StackOverflowError
	at java.io.FilterReader.read(FilterReader.java:65)
...
	at clojure.tools.reader$read.invoke(reader.clj:727) ... repeat this line forever...
```

**Comment by jessitron** [comment]
This is fixed if I add an exclusion to the clix plugin in the project.clj, like so:

```
-                   :plugins [[com.keminglabs/cljx "0.3.1"]
+                   :plugins [[com.keminglabs/cljx "0.3.1" :exclusions [org.clojure/clojure]]
```

I have no idea what other effects this exclusion might have, or else I'd pull-request it.

**Comment by w01fe** [comment]
Thanks for the heads up and the proposed fix.  Not sure what's going on with this (we're still on lein 2.4.3), but I don't see any reason not to add the exclusion.  Does #185 work for you (also bumped a couple other deps)?  Thanks!

**Comment by jessitron** [comment]
Yes, the bump-deps branch compiles! Thank you.

**Comment by w01fe** [comment]
Awesome, thanks again for the report and fix!
