### ISSUE TITLE
Atom schema

### ISSUE THREAD

**Issue by coltnz** [Prismatic/schema#186]
Hi seems a reasonable idea to match atom containers? 

````clojure
(s/defrecord Searches [cassandra :- cassandra/Connection
                       search-ttl-secs :- Long
                       search-cache :- (s/atomic TTLCache)]
````
````clojure
(clojure.core/defrecord AtomicSchema [t]
  Schema
  (walker [this]
          (clojure.core/fn [x]
            (if (and (instance? IAtom x) (= (type @x) t))
              x
              (schema.macros/validation-error this x (list 'and (list 'instance? IAtom x) (list 'instance? t (type @x)))))))
  (explain [this] (list 'and (list 'instance? IAtom this) (list 'instance? t this))))

(clojure.core/defn atomic
  "A value that must be in an atom of type t."
  [t]
  (AtomicSchema. t))
````

**Comment by w01fe** [comment]
It's not unreasonable, but maybe makes more sense to create a generic "reference" schema that can work on futures, atoms, and other reference types?  You could always add the specific reference type check using e.g. `s/both`.  Thoughts?  PR welcome.

**Comment by loganlinn** [comment]
:+1: For generalizing to refs. `IDeref` is the actual abstraction we care about.

As a heads up, `IDeref` an [interface in Clojure](https://github.com/clojure/clojure/blob/1242c4878f3d4ef30535a22f6c74144637504fbe/src/jvm/clojure/lang/IDeref.java) and [protocol in ClojureScript](https://github.com/clojure/clojurescript/blob/7d2565026f1478d0cd2bfa847763c1bd00075561/src/cljs/cljs/core.cljs#L316-L317), so well need to check `(implements? IDeref x)` and `(satisfies? IDeref x)` respectively.

**Comment by coltnz** [comment]
I considered this, but I had a specific contract in this case with a swap!able cache. However, this is probably an edge case and the more general case of just deref-ing with the s/both for specificity is probably superior to supporting all reference types.

Do we like s/ref as a name?  Hmm what about an optional arg. 

````clojure
(s/defrecord Searches [cassandra :- cassandra/Connection
                       search-ttl-secs :- Long
                       search-cache :- (s/ref TTLCache :atom)]
````

**Comment by w01fe** [comment]
I think s/ref seems like it would be specific to clojure.core/ref, so maybe `reference` or perhaps `derefable`?  My preference is top opt for composability over the optional arg -- you can always define your own shortcut for `(defn atom-schema [element-schema] (s/both (ref element-schema) (s/pred (partial instance? Atom) 'atom?)))`.

**Comment by coltnz** [comment]
Having let this sit a bit doing I disagree "IDeref is the actual abstraction we care about", its just a generic container.  (Also don't get the composabilitiy argument for something thats optional .. ). 

When I deref something, I have a particular behaviour in mind. I assert it would be bad for someone to pass in atom instead of a ref and for Schema to allow and the code to fail on swap!

My above sample is working fine for us.
````

**Comment by loganlinn** [comment]
> When I deref something, I have a particular behaviour in mind. I assert it would be bad for someone to pass in atom instead of a ref and for Schema to allow and the code to fail on swap!

`IDeref` is intentionally separate from other protocols/interfaces for writing to the ref types, like `ISwap`. You can write functions over IDeref abstraction that do not care if passed an atom or ref, or even reified object, etc.

I think a case in point is that [`IRef`](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/IRef.java) is the interface to implement for `set-validator!` support and it extends the `IDeref`interface. 

Specific situations that do care about specific write abstractions, like the one you mentioned, it's trivial to combine with `s/both` as @w01fe suggests. Its better for the library to maximize utility by remaining generalized in situations like these.

**Comment by coltnz** [comment]
Yep IRef might be useful, but thats cheating, we're talking about IDeref. Can you find a use for that with Schema?

**Comment by loganlinn** [comment]
Only intended to point out it has parallels to a ref schema. Not suggesting
we use it.

**Comment by w01fe** [comment]
As mentioned in #284, decided to go for the plain old `atom` schema after all -- sorry for the back and forth, and thanks for your thoughts on this.
