### ISSUE TITLE
check has different return type when plan is nil vs invalid

### ISSUE THREAD

**Issue by lvh** [Prismatic/schema#187]
`check` sometimes returns a `PersistentArrayMap` and sometimes returns a `ValidationError`. This caused a really nasty, hard-to-track down bug for me; partially because the `ValidationError` tries really hard not to look like an exception.

Example code:

```clojure
(ns schema-examples
  (:require [schema.core :as s]))

(def Example
  {:a s/Str})

(prn (map (juxt identity type str)
          [(s/check Example {:a 1})
           (s/check Example nil)]))
;; =>
([{:a (not (instance? java.lang.String 1))}
  clojure.lang.PersistentArrayMap
  "{:a (not (instance? java.lang.String 1))}"]
[(not (map? nil))
  schema.utils.ValidationError
  "schema.utils.ValidationError@46424893"])
```

I'd use some of the as-humanly stuff from e.g. cddr/integrity, but I have some custom schema elements that it doesn't understand.

**Comment by lvh** [comment]
I can't use `validation-error-explain` for this either; that doesn't work on the `PersistentArrayMap`. Is there an API I'm missing?

**Comment by w01fe** [comment]
`s/check` returns nil if your data validates, so any value is indicative of an error  -- as the docstring says, the error return value has the same structure as your data, with ValidationErrors at the leaves describing the failures.  The goal is that just turning a non-nil return value into a String should provide a programmer-readable error message.  What were you expecting from the response?

**Comment by lvh** [comment]
I was indeed hoping that any non-nil return value being turned into a string would provide a programmer-readable error message, but e.g. for the example of `nil` above, all you get is `"schema.utils.ValidationError@46424893"`.

**Comment by w01fe** [comment]
Try `pr-str` instead?

```clojure
(prn (map (juxt identity type pr-str)
          [(s/check Example {:a 1})
           (s/check Example nil)]))
=>> ([{:a (not (instance? java.lang.String 1))} clojure.lang.PersistentArrayMap "{:a (not (instance? java.lang.String 1))}"] [(not (map? nil)) schema.utils.ValidationError "(not (map? nil))"])
```

**Comment by lvh** [comment]
Ah! I could've sworn I tried that... But that resolves the issue; thanks!

**Comment by w01fe** [comment]
No problem -- it is a bit confusing.  I don't think there's a good reason
why ValidationError shouldn't have a useful toString method as well as / in
place of the print-method it has currently.
