### ISSUE TITLE
schema compilation fails for my project

### ISSUE THREAD

**Issue by sveri** [Prismatic/schema#194]
Hi,

I have a project with some dependencies, I wanted to include schema now, but when I add it to the project.clj and fire up a repl I get this error:

```clojure
#<CompilerException java.lang.RuntimeException: No such var: sm/protocol, compiling:(plumbing/fnk/schema.clj:22:13)>
```

You can find the project file here: https://github.com/sveri/siwf/blob/integrating_schema/project.clj

Not sure what might be causing this, any help is appreciated.

**Comment by w01fe** [comment]
Sounds like you're using incompatible versions of schema and plumbing. 

Try bumping to a plumbing version `0.3.4` or greater or going back to a schema version `0.3.7` or lower.

**Comment by sveri** [comment]
Indeed, it was a dependency problem. I have ring-transit in my project.clj, which imports an older plumbing version, so I changed my project.clj to look like this:

    ...
    [prismatic/plumbing "0.4.1"]
    [prismatic/schema "0.4.0"]
    [ring-transit "0.1.3" :exclusions [prismatic/plumbing]]

Thank you for hinting me into the right direction. 

Maybe it is possible to give a better error message in such cases?

**Comment by w01fe** [comment]
Great!  I'm not sure how to do that without leaving behind versions of the removed functions forever -- they were deprecated for almost a year before removing them.  Any suggestions?

**Comment by sveri** [comment]
Well, I don't know anything about the internals of schema and plumbing. That aside, as a client of your API I would wish something like this:

    #<CompilerException java.lang.RuntimeException: No such var: sm/protocol, compiling:(plumbing/fnk/schema.clj:22:13)>
    Probably there is a dependency version mismatch due to other libraries using an older version, see here: <link> for more information

This of course only makes sense if you can know what the root cause most probably is.

**Comment by w01fe** [comment]
Thanks.  That does sound ideal, but unfortunately the loading/compilation process is driven by Clojure so I'm not aware of any easy ways to hook into that to provide an error message like that, besides leaving behind stubbed versions of the removed functions indefinitely.
