### ISSUE TITLE
nil successfully validates as a collection

### ISSUE THREAD

**Issue by wkalt** [Prismatic/schema#195]
I see this inconsistency:

foo.core=>  (s/validate {:a s/Str} nil)
ExceptionInfo Value does not match schema: (not (map? nil))  schema.core/validate (core.clj:161)

foo.core=> (s/validate [{:a s/Str}] nil)
nil

where the difference is that in the second case the schema is a collection. The first case looks right, I think the second case should fail validation.

**Comment by loganlinn** [comment]
This is intentional/known behavior because `nil` is a valid sequence in Clojure. Please see #69, #175
