### ISSUE TITLE
is this still alpha?

### ISSUE THREAD

**Issue by boxxxie** [Prismatic/schema#197]
just wondering, because this library is at almost 600 commits and a few years old.

**Comment by w01fe** [comment]
We're using schema very widely in production, and take care to provide a path of compatibility for our users.  So while I would consider schema beyond typical alpha-quality, there is still one more fundamental generalization we would like to consider before 1.0, which may incur some downstream breakage (but potentially not worse than a typical major version bump).  

Does that answer your question?

**Comment by juhovh** [comment]
Just curious, would you mind to shed some light on what generalization are we talking about? Would be easier to help and/or prepare.

**Comment by w01fe** [comment]
Sure, it's here in-progress (https://github.com/Prismatic/schema/compare/declarative-schema-specs).  The basic idea is to make the internals of schema more declarative, which makes it much easier to define new schema types, and create new applications for schemas (such as generative testing).    

Comments on the overall design are welcome at this point.  All the tests pass, but there are still a bunch of TODOs that we probably need to wrap up before it makes sense to ask for external contributions / real-world testing.
