### ISSUE TITLE
=> and =>* are unfortunate macro names

### ISSUE THREAD

**Issue by geraldodev** [Prismatic/schema#203]
Why ? Because is the prompt of our beloved repls.

(s/explain (s/fn-schema stamped-names))
==> (=> (record user.StampedNames {:date java.lang.Long, :names [java.lang.String]})
        [java.lang.String])

You can tell by the docs where the author had to increase the size of the prompt to differentiate from the =>.

Please rename and deprecate.

Geraldo

**Comment by w01fe** [comment]
Isn't `user>` the repl prompt?  `==>` is just an idiom used in the docs to indicate what a form evaluates to.

**Comment by geraldodev** [comment]
No, both leiningen and bare clojure repl uses user=> 

It's really confusing imho.

**Comment by w01fe** [comment]
Thanks for your input.  IMO this probably doesn't merit a breaking change, but we'll keep our ears open and if this seems to be a common concern we'll reconsider.
