### ISSUE TITLE
Compile warnings using [org.clojure/clojurescript "0.0-3208"]

### ISSUE THREAD

**Issue by hipitihop** [Prismatic/schema#206]
WARNING: ->ValidationError at line 68 is being replaced at line 80 file:/home/<user>/.m2/repository/prismatic/schema/0.4.0/schema-0.4.0.jar!/schema/utils.cljs
WARNING: ->NamedError at line 89 is being replaced at line 101 file:/home/<user>/.m2/repository/prismatic/schema/0.4.0/schema-0.4.0.jar!/schema/utils.cljs
WARNING: ->ValidationError at line 68 is being replaced at line 80 run/test/compiled/test/schema/utils.cljs
WARNING: ->NamedError at line 89 is being replaced at line 101 run/test/compiled/test/schema/utils.cljs

**Comment by w01fe** [comment]
Already fixed (but not yet released) in #193
