### ISSUE TITLE
more distinct names for Schemas

### ISSUE THREAD

**Issue by ikitommi** [Prismatic/schema#210]
hi,

Would be great if schemas would have more distinct names. Currently one can create multiple schemas into separate namespaces with same name but with different value. If schema name would contain the namespace also, so they would be unique and by so, more useful for documentation purposes.

Ideas:
1) change the current `:name` to contain the namespace-part too (a breaking change, bad)
2) add more meta-data to schemas, `:full-name` with the ns + the file-name & line-number where it was defined. Would help a lot on the systems that use Schema for documentation.

would be happy to create a PR for the 2 if that is a valid approach.

https://github.com/frankiesardo/pedestal-swagger/issues/7

https://github.com/metosin/ring-swagger/blob/6c0ada07e146a3247f58f92347d509e8f9d959d6/src/ring/swagger/core.clj#L104-L109

**Comment by w01fe** [comment]
Approach 2 sounds good -- not sure what you're thinking exactly, but I think we would prefer more structured info (e.g., match the keys put by Clojure on vars) to a single full-name field with all the info crammed into one place.  PR welcome -- thanks!
