### ISSUE TITLE
protocol as fn return type

### ISSUE THREAD

**Issue by d-t-w** [Prismatic/schema#214]
There has been a change in behaviour between v0.3.1 and v0.4.0 and I'm not entirely sure if it is a bug, there is a simple work-around.

v.0.3.1 supports a fn return type which is a protocol in a different namespace:

````clojure
(s/defn ->connection :- cassandra/Connection
  "Provide a new connection"
  [config :- cassandra/Config]
  (map->Connection {:config config}))
```

now, in v.0.4.0 that will cause:

````
Caused by: java.lang.IllegalArgumentException: No implementation of method: :walker of protocol: #'schema.core/Schema found for class: clojure.lang.Symbol
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:555)
````

the work-around is to explicitly add a s/protocol:

````clojure
(s/defn ->connection :- (s/protocol cassandra/Connection)
  "Provide a new connection"
  [config :- cassandra/Config]
  (map->Connection {:config config}))
````

Seems fairly minor, but I guess there may be other related cases.

**Comment by w01fe** [comment]
Sorry for the inconvenience.  This is an intentional breaking change in 0.4.0

https://github.com/Prismatic/schema/blob/master/CHANGELOG.md

**Comment by d-t-w** [comment]
Thanks I should have checked the changelog.md!

**Comment by w01fe** [comment]
No worries, thanks for the report  :)
