### ISSUE TITLE
Protocols no longer work as schemas

### ISSUE THREAD

**Issue by jessitron** [Prismatic/schema#222]
In 0.3.7, I could use Schema as a schema.

    user=> (require '[schema.core :as s])
    user=> (s/defn foo [s :- s/Schema])
    nil
    user=> (s/set-fn-validation! true)
    true
    user=> (foo s/Keyword)
    nil
    user=> (foo "bar")
ExceptionInfo Input to foo does not match schema: [(named (not (satisfies? (clojure.core/deref #'schema.core/Schema) "bar")) s)]  user/eval9775/foo--9778 (form-init9101381405213677541.clj:1)

In 0.4.3, if I try to use a protocol as a Schema, it gets treated as a map-schema. This is not listed as a breaking change in the changelog.
Plus, the error messages are incredibly confusing.

For example:

    user=> (require '[schema.core :as s])
    user=> (s/defn foo [s :- s/Schema])
    RuntimeException More than one non-optional/required key schemata: [clojure.lang.APersistentMap clojure.core$long clojure.core$short clojure.core$floats clojure.core$int clojure.core$booleans clojure.core$float clojure.core$char clojure.core$byte clojure.core$longs clojure.core$ints clojure.lang.APersistentVector java.lang.Class clojure.core$double java.util.regex.Pattern clojure.core$chars clojure.core$bytes clojure.core$doubles clojure.core$boolean clojure.core$shorts clojure.lang.APersistentSet]  schema.core/find-extra-keys-schema (core.clj:712)

On other protocols the error is different:

    (defprotocol Banana (peel [me]))
    (s/defn bar [b :- Banana])
    IllegalArgumentException No implementation of method: :walker of protocol: #'schema.core/Schema found for class: clojure.lang.Symbol  clojure.core/-cache-protocol-fn (core_deftype.clj:544)

not AS crazy but it's still treating the protocol as a map-schema, so it's a matter of which error it hits first.

Workaround is, I can construct a protocol-implementation schema 

    (s/defn foo [s :- (s/pred (partial satisfies? s/Schema) "is a schema")])

which is fine, but whoa the error messages did not lead me there. And it's an undocumented breaking change.

**Comment by w01fe** [comment]
Apologies for the unclear documentation. The breaking changelog 0.4.0 entry removing "bare ^Protocol annotations" complected both the removal of bare protocols as schemas, as well as metadata-style schemas that are not valid Clojure type hints.  I didn't think `:- Protocol` was ever a documented feature so didn't think anyone was using it (you're the first to notice).  Anyway, I'll update the changelog to split out those two points.  

I apologize for the poor error messages as well.  For context, protocols are just maps under the hood, and we made a poor design choice early on using a hack to detect when a map happened to look like a protocol, in the special case of type-hinting functions.  With that removed, the protocol is interpreted as a map schema.  A patch is welcome to make the map walker throw if the map schema looks like a protocol.

**Comment by w01fe** [comment]
Also, `s/protocol` has been there since the initial release -- that's the preferred way to hint a protocol.  

```clojure
(s/defn foo [s :- (s/protocol s/Schema)])
```

**Comment by w01fe** [comment]
Does this explain the changes more clearly? 

https://github.com/Prismatic/schema/commit/9e442d98ef21147d45388163e2c6734264dc4c8d

Thanks for the report and apologies again for the difficult debugging experience.

**Comment by jessitron** [comment]
oh thanks! I didn't know s/protocol. That's much prettier. 

And yes, the new changelog is very clear. Thank you!
