### ISSUE TITLE
Value returned from walker function ignored?

### ISSUE THREAD

**Issue by tdavis** [Prismatic/schema#224]
I'm trying to write a schema type that will coerce valid keys to a value in a map, so I could do say ``(validate (->ThingNamed) :foo)`` and end up with the value at ``(:foo @registry)`` but the return value is always ``:foo``. The error case seems to work fine as my custom error is used for bad keys. What am I doing wrong?

```clojure
(defrecord ThingNamed []
  s/Schema
  (s/walker [this]
    (fn [name]
      (if-let [thing (name @registry)]
        thing
        (macros/validation-error this name (list 'in (keys @registry) (utils/value-name name))))))
  (explain [this] (list 'in (keys @registry))))
```

**Comment by w01fe** [comment]
`validate` always returns the original value: https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx#L178

If you want to do coercion, you should use use `coercer` instead -- see the Coercion section in the README.  You coerce to the real schema you want (not a custom schema type) and your lookup logic goes into the coercion-matcher.

**Comment by tdavis** [comment]
Okay, so I'm probably just dense here, but I'm having trouble putting the pieces together. Here's a realistic example of what I'm trying to accomplish, albeit in the wrong way:

```clojure
(defrecord FileContents [base-path]
  s/Schema
  (s/walker [this]
            (fn [x]
              (if (.exists (io/file base-path x))
                (io/file base-path x)
                (macros/validation-error this x (list 'exists (utils/value-name x))))))
  (s/explain [this] (list 'file 'relative 'to base-path)))

(defn fc->content [fc]
  (slurp fc))

(defn fc-coercion-matcher [schema]
  (if instance? FileContents schema) fc->content)

(def Example {:path (FileContents. "/tmp")})

(def parse-example (coerce/coercer Example fc-coercion-matcher))
```
In this example, I want to be able to coerce an ``Example`` to contain the contents of a file relative to ``/tmp``, instead of the string, say, ``foo.txt``. Unfortunately ``(parse-example {:path "foo.txt"})`` fails for (at least) a couple reasons:

1. Coercion happens before validation
2. Even if it didn't, the coercer wouldn't have access to ``base-path``. 

My thought at this point is I need the coercer to actually do the file reading and I'd just have ``(def Example {:path s/Str})``. But that leaves me with a couple other questions:

1. How can the coercion matcher know which ``s/Str`` fields should be coerced? Do I still need some manner of custom Schema?
2. How do I "bind" the coercion aspect to the schema in the case where I'm just using ``def`` or ``defschema`` and the actual validation and such is being handled by something like Compojure? Is that just not possible?

**Comment by w01fe** [comment]
Schemas are meant to describe your data in a declarative way.  You're trying to use them as a procedural specification of how to get your data, which is where the impedance mismatch is coming in.  

Something like this should work:

```clojure
(s/defschema FileContents 
  (s/named String "file contents")) ;; by naming it, you now have a special schema to answer (1)

(defn fc-coercion-matcher [schema]
  (when (identical? FileContents schema) slurp))

(def parse-example (coerce/coercer {:title String :contents FileContents} fc-coercion-matcher))

(parse-example {:title "HI!!" :contents "http://www.december.com/html/demo/hello.html"})

;; ==> {:title "HI!!", :contents "<!DOCTYPE html PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n<html>\r\n <head>\r\n  <title>\r\n   Hello World Demonstration Document\r\n  </title>\r\n </head>\r\n <body>\r\n  <h1>\r\n   Hello, World!\r\n  </h1>\r\n  <p>\r\n   This is a minimal \"hello world\" HTML document. It demonstrates the\r\n   basic structure of an HTML file and anchors.\r\n  </p>\r\n  <p>\r\n   For more information, see the HTML Station at: <a href= \r\n   \"http://www.december.com/html/\">http://www.december.com/html/</a>\r\n  </p>\r\n  <hr>\r\n  <address>\r\n   &copy; <a href=\"http://www.december.com/john/\">John December</a> (<a\r\n   href=\"mailto:john@december.com\">john@december.com</a>) / 2001-04-06\r\n  </address>\r\n </body>\r\n</html>\r\n"}
```

So FileContents describes the data it expects to see after coercion (in this case, a string), and the coercer says how to transform whatever you've got into that format.  

For (2), I don't know much about Compojure and how it integrates with schema, but you'd probably have to configure that to use coercion somehow.  You could look into fnhouse, which is built to work with coercion.

**Comment by tdavis** [comment]
Great! I figured I was using it wrong to some extent and have since changed my approach a bit. This has been very instructional, thanks for your speedy help!

**Comment by ikitommi** [comment]
If you are using Compojure with Schema, you might want to check [Compojure-api](https://github.com/metosin/compojure-api). Coercion with it: https://github.com/metosin/compojure-api#coercion
