### ISSUE TITLE
Schemas for function parameters of higher order functions

### ISSUE THREAD

**Issue by expez** [Prismatic/schema#229]
Is this doable?

**Comment by kernelp4nic** [comment]
Something like [s/defn?](https://github.com/Prismatic/schema/blob/27668958099092a17b5c31db68824cda0914d08f/src/cljx/schema/core.cljx#L1131)

**Comment by expez** [comment]
I suppose I could've been a bit clearer about what's wanted here.  Sorry about that.

For functions that take a function as an argument, I'd like to annotate the function parameters of that function.

**Comment by w01fe** [comment]
https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx#L958 

but please be aware they are only for documentation purposes (no validation is done).  For an example, you can search for `fn-schema` in the readme.

**Comment by expez** [comment]
Thanks, I had no idea `=>` existed!
