### ISSUE TITLE
Coerced errors to string

### ISSUE THREAD

**Issue by nha** [Prismatic/schema#230]
Hello,

First of all, many thank for doing Schema !
I am starting a Clojure project, and having coercion is really nice.
I use it with compojure, but I am wondering if I could reuse the error messages of the coercer in my API responses. Here is what I have so far :

```
(def simple-schema {:name s/Int })

(def parse-request
  (coerce/coercer simple-schema coerce/string-coercion-matcher))

(defn request-handler
  "receives a compojure request"
  [{ :keys [id] :as params }]
  (let [coerced (parse-request params)]
    (if (:error coerced)
      (do (println "ERROR! " (:error coerced))                           ;; {:id (not (integer? AAA))}
           (response {:status 400 :body {:error (:error coerced)}})) ;; This fails. How can I provide nice error messages ?
      (do (println "Well done!")
          (response {:status 200 :body "OK"}))))
```

Note : I am using the wrap-json-response middleware, but anything would be fine. Hopefully I'm just missing something.

**Comment by w01fe** [comment]
Have you tried calling `str` on the error?

**Comment by nha** [comment]
Hello,

Thank you for your quick reply :)

Yes it works with `str`, sorry I did not explain it right.
It works with `str` in the sense that I get something like : ```{"status":400,"body":"{:error {:id (not (integer? AAA))}}"}```, which doesn't look like a JSON (unfortunately only the API uses Clojure for now).

In other words, is there a way to make is look like (for instance) "{status:400, body:{error : { id : "not integer AAA"}}}" ? It would allow for instance to display nice error messages.

**Comment by w01fe** [comment]
machine-readable error messages are not a goal currently, but you could try `schema.utils/validaiton-error-explain` in place of `str` perhaps.

**Comment by ikitommi** [comment]
example here: https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/middleware.clj

**Comment by nha** [comment]
Thank you @w01fe @ikitommi  I'll have a look, that seems to be what I was looking for !
