### ISSUE TITLE
Namespace conflict with swagger-docs middleware

### ISSUE THREAD

**Issue by calumats** [Prismatic/schema#231]
Hi,

I've been trying to debug an issue with building an uberjar of a simple hello world web app I have. The exception I get is `Unable to resolve symbol: missing-required-key in this context`. The issue seems to be in the nested macro which references swagger-docs and is conflicting with Schema. Here is the relevant code snippet:

```clojure
(ns server.api
  (:require [aleph.http :as http]
            [compojure.route :as route]
            [compojure.api.swagger :refer [swagger-ui swagger-docs]]
            [compojure.api.core :refer [api GET*]]
            [compojure.api.meta :refer [middlewares]]
            [ring.util.http-response :refer [ok not-found]]
            [schema.core :as s]
            [server.logging :refer [wrap-exception-logging wrap-request-logging info]]))

(s/defschema Greeting
  {:hello s/Str
   s/Keyword s/Any})

(defn app [db]
  (api
   {:format {:formats [:json-kw]}}
   (middlewares [wrap-request-logging
                 wrap-exception-logging]
                (swagger-ui "/docs" :swagger-docs "/endpoints")
                (swagger-docs "/endpoints"
                 {:info {:title "Hello World Api"}})

                (GET* "/greet" []
                      :summary "Greets someone by name."
                      :description "Greets a person by name, telling them about
                                    the database configuration we're using as well."
                      :return Greeting
                      :query-params [name :- s/Str]
                      (ok {:hello name :with-db db}))

                (route/not-found (not-found {:error "Page not found."})))))
```

If I remove the `swagger-docs` line and the one below it, the uberjar builds just fine. This behaviour happens with Schema v 0.4.4 and 0.4.3. I've tried adding a namespace exclusion to project.clj like so:

```clojure
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [compojure "1.3.4" :exclusions [prismatic/schema]]
                 [ring "1.3.2"]
                 [aleph "0.4.0"]
                 [prismatic/schema "0.4.4-SNAPSHOT"]
```

I apologize if this is the wrong venue for this post, but I was advised that it might be worth making an issue here in case this was an issue with Schema.

I've omitted the rest of the project since I can't easily put all these files in an issue. If you would like a copy of the project, let me know and I'll try and upload it somewhere.

I posted on [stackoverflow](http://stackoverflow.com/questions/30935458/schema-causing-uberimage-build-failure) with this issue and there is more detail there on the error I get and what I've tried.

**Comment by w01fe** [comment]
It the issue goes away when you comment out `swagger-docs`, sounds like it's probably an issue with `swagger-docs`.  Did you create an issue over there?

**Comment by calumats** [comment]
Good point. I'll open an issue over there.
