### ISSUE TITLE
fn macro is inaccessible in Clojure versions in which CLJ-1195 is not fixed

### ISSUE THREAD

**Issue by chairmanK** [Prismatic/schema#232]
Is there a way to get the functionality of the `schema.core/fn` macro when it is unmapped from the namespace? If it isn't accessible, a macro alias would be a helpful workaround.

**Comment by w01fe** [comment]
The tests are currently passing in Clojure 1.5.1 and Clojure 1.6.0 -- can you please provide an example that fails?

**Comment by chairmanK** [comment]
I observed that attempting to use `schema.core/fn` gave me

    CompilerException java.lang.RuntimeException: No such var: s/fn, compiling (/tmp/form-init****.clj:1:1)

while the `defn` macro worked as expected. However, I was not able to reproduce this problem outside of a particular classpath environment, and after `lein clean` the problem resolved there. So I am unable to reproduce. Sorry for the distraction; I'm closing this issue.

**Comment by chairmanK** [comment]
I think that this is a duplicate of https://github.com/Prismatic/plumbing/issues/74
