### ISSUE TITLE
Allow schema.core/either schema to have a `name` argument to improve error message

### ISSUE THREAD

**Issue by mrrodriguez** [Prismatic/schema#235]
I've seen this topic brought up once or twice, e.g. https://github.com/Prismatic/schema/issues/36.

I understand that schema.core/either is not a very informative schema to use in some situations because the validation does not have any idea which schema was not matched - it just didn't match any of them.

I see how schema.core/conditional often can be nice to narrow down the cases better for error reporting.  However, there are times when s/condition can get clunky and s/either would be nice to be able to use.

I see the issue with s/either error message reporting to be somewhat analogous to schema.core/pred schema.  Without the `pred-name` argument, the error message can be fairly difficult to get any insight from.

So, in the (rare?) cases where s/either is used, why not allow for a `name` to be passed in like s/pred (and schema.core/one etc)?  The error message could be the useful bit of information used in the error message to help make the s/either have something worthwhile to report upon failure.

I see that the signature of s/either isn't exactly friendly to extension right now, but we could probably work something out...  Anyways, I'm curious for your feedback on this.

**Comment by w01fe** [comment]
That's an interesting suggestion, but I also don't see an easy way to extend `s/either` to take a name.  Of course, you can always wrap the `s/either` in an `s/named` yourself to get this behavior.  We're open to suggestions, but would rather not do a breaking change or add another different variant of `s/named-either` or some such.  

If you have suggestions for making `s/if` and `s/conditional` less clunky, we'd definitely be interested in those.

**Comment by mrrodriguez** [comment]
I don't know how I missed it before, but I see there is already quite a history of discussing `either` schema error messages beyond the link I made.

https://groups.google.com/forum/#!msg/prismatic-plumbing/w7QyEUuaAsA/dvMoZk7N5lYJ and
https://github.com/Prismatic/schema/issues/235

seem to be the same topic.


However, with that explained you enlightened me in this comment that I can wrap s/named around schema that do not support a name to get a name in the error message.  I think that is good enough to serve the need for now anyways.  This is definitely nice to know.

I appreciate your feedback again!


---

I'll add to this what I mean by "clunky" with s/if and s/conditional just for completeness.  I do not think they are clunky when they are appropriate.

--

Non-clunky example:

```clj

(validate (conditional map? {:a Str}
                       vector? [Str])
          {:a "hi"})
```

The conditions are clearly distinct cases where the given input does fall into a specific category.

--

Cluncky example:

```clj
(validate (conditional :a {:a Str
                           :b Str}
                       :b {:b Str
                           :c Str})
          {:a "hi"
           :b "world"})
```


This is really contrived, but the point is that the conditional is redundant.  It is also really redundant to do some sort of `(either SomeClassType1 SomeClasstype2)` with conditional instead:

```clj

(validate (conditional (partial instance? SomeClassType1) SomeClassType1
                       (partial instance? SomeClassType2) SomeClassType2)
          (->SomeClasstype1))
```

I know this could potentially use s/pred instead, but that is more unstructured.

--

Also, I'm using s/conditional in the examples when I know for cases of 2 conditions I could use s/if, but this is just demonstrating.

---

**Comment by w01fe** [comment]
Thanks for the details.  The class example is one we've thought about but
haven't created anything yet; for the map case, we usually ensure there's a
`:type` key to dispatch on, and have an unreleased schema type that's
optimized for this use case.

**Comment by mrrodriguez** [comment]
That is good to hear that there is something in the works for the map case.  That'd likely be useful for me as well.

I think the "either" Class case could definitely be valuable.  It is probably a bit easier to express the error in that class since I'd imagine there'd be some reasonable number of class names to display when nothing matched.

**Comment by w01fe** [comment]
Cool, we'll think more about that.  In the mean time, the map thing is here:

https://gist.github.com/w01fe/a39fe486cf011be51b2c

(there are a few rough edges we'd like to smooth out before adding it to
schema proper).

**Comment by mrrodriguez** [comment]
Thanks for the link! I'll check it out. Sorry for the delayed response.

**Comment by NicoleRauch** [comment]
Actually, what was very, very helpful for me was to change the error report to contain the non-matching element, in this way:

--- a/src/cljx/schema/core.cljx
+++ b/src/cljx/schema/core.cljx
@@ -480,7 +480,7 @@
                 (if-not sub-walkers
                   (macros/validation-error
                    this x
-                   (list 'some (list 'check '% (utils/value-name x)) 'schemas))
+                   (list 'some (list 'check '%  x (utils/value-name x)) 'schemas))
                   (let [res ((first sub-walkers) x)]
                     (if-not (utils/error? res)
                       res

Maybe this would be worthwhile to integrate in some way or another?

**Comment by w01fe** [comment]
Closing since `either` is now deprecated.
