### ISSUE TITLE
Schema not working for clojure 1.6.0?

### ISSUE THREAD

**Issue by schmfr** [Prismatic/schema#238]
I tried to use schema 0.4.3 with clojure 1.6.0 but validation seems to be ignored. I got
```clojure
user=> (s/validate java.lang.String 42)
42
```
With clojure 1.7.0 everything works fine. Is this reproduceable for others?

**Comment by w01fe** [comment]
That's very odd -- thanks for the report.  Can you provide a reduced test
case?  (The above example works fine for me under a bare 1.6.0 repl with
just schema).

**Comment by schmfr** [comment]
The validation fails when I have clojure 1.6.0, schema 0.4.3 and a particular lib of our company in the project.clj. With clojure 1.7.0 or without the lib everything works fine. The lib itself uses clojure 1.6.0 and schema 0.3.7 and does no fancy stuff (no manipulation of other namespaces). It just requires schema.core in some source files and additionally schema.macros in one source file. A lein deps-tree shows all the dependencies for the lib execpt the entry for schema 0.3.7 which is missing. This is totally confusing for me and I cannot explain it. Moreover, I dont know how to investigate this problem further.

**Comment by w01fe** [comment]
That is very strange indeed.  Thanks for the details.  Not sure if we can do anything without the ability to reproduce though; please let us know if you manage to track it down further.

**Comment by schmfr** [comment]
I will ask the author of the lib next week.

**Comment by schmfr** [comment]
Unfortunately, due to a lack of time I can not investigate the problem deeper. I'm sorry! Recently we've had some strange problems when using different versions of taoensso libraries in our libs. This might be a starting point for a deeper investigation.
