### ISSUE TITLE
Coercions for Java types

### ISSUE THREAD

**Issue by lightsaber** [Prismatic/schema#241]
Disclaimer: Java programmer poking around in clojure, please forgive the ignorance of concepts and terminology.

So, I'm sure this is covered but because I am new to clojure I can't seem to identify what I am looking for.  I am bringing data out of MongoDB where the generated id is of type org.bson.types.ObjectId.  Schema doesn't know what to do with this value, so it tells me there is no walker for it.  At this point I'm not sure if I should create a new schema to contain that ObjectId value, or create a custom coercion, or ... something else.

I'd be really happy if someone could point me at the right spot in the documentation

**Comment by w01fe** [comment]
Do you just want to validate the object as it is, or coerce it to some other type?  

Can you provide the code you're using?  If you're trying to treat an instance of ObjectID as a schema, something is wrong.   Note that you could use the *class* `org.bson.types.ObjectId` as a schema that would validate instances of that class, however, or use `(s/eq ...)` to match for equality against a *particular* ObjectId.

**Comment by lightsaber** [comment]
So I have a schema that I've defined as:
`(s/defschema User {:_id ObjectId, :user_id String, :first_name String, :last_name String})`

I am querying mongo for a user:

    (defn find
         [criteria]
         (let [conn (mg/connect {:host "192.168.59.104"})
                                    db   (mg/get-db conn "users")]
 
              (s/validate User (mc/find-one-as-map db "users" { :user_id "pnishizawa" })))
      )

When I validate the User, it says:
INFO: Opened connection [connectionId{localValue:930, serverValue:248}] to 192.168.59.104:27017
java.lang.IllegalArgumentException: No implementation of method: :walker of protocol: #'schema.core/Schema found for class: org.bson.types.ObjectId
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
	at schema.core$eval6790$fn__6802$G__6781__6807.invoke(core.clj:105)
	at schema.coerce$eval8706$coercer__8707$fn__8708$fn__8709.invoke(coerce.clj:31)
	at schema.utils$memoize_id$fn__6517.invoke(utils.clj:49)
	at schema.core.MapEntry.walker(core.clj:666)
	at schema.coerce$eval8706$coercer__8707$fn__8708$fn__8709.invoke(coerce.clj:31)
	at schema.utils$memoize_id$fn__6517.invoke(utils.clj:49)
	at schema.core$map_walker$iter__7368__7372$fn__7373.invoke(core.clj:727)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
	at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at clojure.core$into.invoke(core.clj:6341)
	at schema.core$map_walker.invoke(core.clj:725)

**Comment by w01fe** [comment]
Thanks for the details, thats very helpful.  It's also very odd -- I don't see how coercer is showing up in the stack trace when you're not mentioning it in this snippet (the `schema.coerce` namespace shouldn't even be *loaded* unless you do so explicitly) -- are you sure this stack trace is from this code?

**Comment by lightsaber** [comment]
It is from this code but I may have changed the code a bit since I last ran it.  I tried to get it back to that state last night but now the server won't start.  I will continue to try to get it back to that point but the message on the IllegalArgumentException was definitely the message I got.  I'm assuming it is because it doesn't know what to do with that object, but I don't know what to do to help it.  Is that where defrecord comes in?

**Comment by w01fe** [comment]
I believe the code you have up there is fine.  It successfully validates for me:

```clojure
user> (s/validate User {:_id (org.bson.types.ObjectId.) :user_id "asdf" :first_name "bob" :last_name "foobar"})
{:_id #object[org.bson.types.ObjectId 0x2e3948ad "55c3919ad4c60adb481041bd"], :user_id "asdf", :first_name "bob", :last_name "foobar"}
```

If you're not used to using a REPL, I would suggest trying that out.  It makes it easy to start small and test each piece before building up to bigger pieces, which is really helpful especially when you're learning the language.

**Comment by lightsaber** [comment]
So you are saying that I should not need to do anything in order to make this work, correct?  Is there a version of the project where this might not have worked.  Schema is being included as part of compojure-api, so I'm wondering if it might be a difference in version.

On a separate note, sorry, I know this isn't related to your project, but I was assuming that running "lein repl" from the directory where my project.clj file is located would allow it to include the dependencies declared in there.  Is that not the case?  I can't import schema.core.

**Comment by w01fe** [comment]
No, I don't believe there is such a version.  I think you were probably using coercions incorrectly when you got that error, but it's hard to say -- if you can provide an error and the actual code that produced it I may be able to help.   

This conversation may be more appropriate for the mailing list, BTW.  

Yes, lein repl should include dependencies; I'm not sure what's going on there.

**Comment by ikitommi** [comment]
If you are getting the error when calling a compojure-api route (uses coersion), you could also write an issue there, with minimal example route.

**Comment by lightsaber** [comment]
That's a good suggestion. I thought the error was coming from the validate but didn't consider that it might be a problem in the routing.  Thanks for the suggestion and thanks for the quick response.
