### ISSUE TITLE
ClassNotFoundException using a record as schema - Any way around?

### ISSUE THREAD

**Issue by rkoch** [Prismatic/schema#249]
Hi,

When trying to set a record as schema for a function parameter, I always get a ClassNotFound exception when starting the system. I believe this is because the HttpClient record is not yet compiled at startup time and thus throwing this error. Is there any way around this issue without AOT'ing the namespace defining the record?

bee.http-client.component.clj (defining record):
```clojure
(s/defrecord HttpClient [config clj-http]
  component/Lifecycle

  (start [component]
    ;; omitted
    )

  (stop [component]
    ;; omitted
    ))
```

bee.http-client.service.clj (using record as schema):
```clojure
(cs/defn send
  [component :- bee.http_client.component.HttpClient
    message]
  ;; omitted
 )
```

Here is the exception I'm getting when starting the REPL with `lein repl` (see [Gist](https://gist.github.com/rkoch/eeda6e2e527beb468c51) for full stack trace):
```edn
#error {
 :cause bee.http_client.component.HttpClient
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.ClassNotFoundException: bee.http_client.component.HttpClient, compiling:(bee/http_client/service.clj:37:1)
   :at [clojure.lang.Compiler load Compiler.java 7239]}
  {:type java.lang.ClassNotFoundException
   :message bee.http_client.component.HttpClient
   :at [java.net.URLClassLoader findClass URLClassLoader.java 381]}]
 :trace
 ;; omitted for better readability (see gist)
 }
```

Or am I using it completely wrong? - I'm a clojure newbie :)

Thanks in advance!

**Comment by w01fe** [comment]
Have you tried requiring `bee.http-client.component` from `bee.http-client.service`?  You have to load the namespace before referencing the class (it's a Java/Clojure thing, don't think there's anything Schema-specific here).

**Comment by rkoch** [comment]
Ah, that solved it!!! :tada: :tada: :tada:

I alway tried to `(:import [bee.http_client.component.HttpClient])` the record, instead of referencing the namespace in the `require` clause. So as I understand it, the compiler only compiles the stuff defined there and assumes that the `import`'ed classes are already compiled.

Thank you very much for the help and the quick response!

**Comment by w01fe** [comment]
You're welcome!  Import just creates a shortcut for the Java class, but the class is actually created by loading the namespace, which is accomplished with the `require`.
