### ISSUE TITLE
CLJS: A significant performance gain by caching validation results via WeakMap

### ISSUE THREAD

**Issue by darwin** [Prismatic/schema#256]
Today I just started using your awesome library in [my project](https://github.com/darwin/plastic), built on top of [re-frame](https://github.com/Day8/re-frame). Thank you. 

I'm validating app-db atom state after every reset! on it.

But I immediately hit a performance issue. My app-db is pretty heavy and contains undo/redo queues which meant incrementally degrading performance because validation code has to go through increasing number full app states after each app-db change. I observed that in my case app-db changes frequently but usually just with a trivial change (a cursor movement, etc.). Validation results should be cached.

I solved this by simple caching using [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)/[WeakSet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet):
https://github.com/darwin/plastic/blob/master/cljs/src/common/plastic/validator.cljs

I just want to point out that you could implement something like this in your cljs version of the library. 

The general idea would be: if WeakMap is available, store mapping of `object` -> `list of successfully validated schemas` in a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap).

Thanks to persistent data structures there is no worry about invalidating the cache, all users could benefit from this caching transparently and almost for free.

**Comment by w01fe** [comment]
Thanks for the suggestion.  This is something we've had on the radar for awhile, but I think the tradoffs are subtle enough in some cases that we've preferred to let users manage the caching as you have rather than try to build it in for now.
