### ISSUE TITLE
schema potentially tags boolean values as primitives

### ISSUE THREAD

**Issue by MichaelBlume** [Prismatic/schema#264]
https://github.com/Prismatic/schema/blob/master/src/clj/schema/macros.clj#L72

Apparently this is incorrect? http://dev.clojure.org/jira/browse/CLJ-701?focusedCommentId=41088&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-41088

**Comment by w01fe** [comment]
Hrm, thanks for the report.

I believe boolean is a valid primitive tag in ClojureScript, however.  We'd
gladly accept a PR that correctly configures these for each platform, but
in the mean time I think a good workaround would be to use the Class
versions when the primitive typehint is not a valid Clojure typehint (which
seems like better style anyway).

**Comment by loganlinn** [comment]
> I believe boolean is a valid primitive tag in ClojureScript

correct https://github.com/clojure/clojurescript/blob/1b7390450243693d0b24e8d3ad085c6da4eef204/src/main/clojure/cljs/core.cljc#L787-L793

**Comment by w01fe** [comment]
As mentioned in #270, I believe that the code is correct as-is for local bindings (e.g., letk; it's only function arguments that restrict which primitive types can be used.) I'm inclined to say this is just a documentation problem then; that we should be clear that you should only use primitive schemas on binding forms where Clojure would accept them as a valid type hint. Thoughts?

**Comment by w01fe** [comment]
#285 adds the documentation updates discussed above; please let us know if this doesn't seem like an adequate resolution to the issue.  Thanks!
