### ISSUE TITLE
Question: validating a function as part of a schema

### ISSUE THREAD

**Issue by xpe** [Prismatic/schema#272]
My use case is that I want to validate a map with callback function. For example: `{:action (fn [] nil)}`.

Clojure has `fn?` -- that's what I use when I use Clojure preconditions. What, if anything, would correspond in schema?

**Comment by w01fe** [comment]
You can always use `(s/pred fn?)`.  Or if you want to be more specific (for documentation purposes only!  has no effect on validation) you can use, e.g. `(s/=> s/Int s/Str s/Str)` for a function that takes two strings and returns an integer.

**Comment by xpe** [comment]
Thanks! Would `s/fn` be useful as well? I was about to try it.

**Comment by w01fe** [comment]
`s/fn` creates a schematized function -- it's like `s/defn` for anonymous functions.  

https://github.com/Prismatic/schema/blob/master/test/cljx/schema/core_test.cljx#L822

https://github.com/Prismatic/schema/blob/master/test/cljx/schema/core_test.cljx#L834

**Comment by xpe** [comment]
I'm now using `(s/pred fn?)` based on you mentioning it.

`(s/=> s/Int s/Str s/Str)` is nice and Haskelly, but the 'for documentation only' caveat seems limiting.

Re: `s/fn`. Were you mentioning it as a solution for my use case? Or just helping me understand it? I currently don't see it helping the use case above.

**Comment by w01fe** [comment]
Just helping you understand.

**Comment by w01fe** [comment]
If you have further questions, please ask them on the mailing list.  Thanks!

**Comment by xpe** [comment]
Thanks!
