### ISSUE TITLE
s/defn returns nil instead of var

### ISSUE THREAD

**Issue by aengelberg** [Prismatic/schema#274]
```clojure
user> (s/defn f :- s/Int [x :- s/Int] (inc x))
nil
```
I would expect it to return `#'user/f` instead of nil. Now I cannot use `s/defn` in conjunction with `clojure.test/with-test`, because that macro expects the enclosed definition to return a new var to test.

**Comment by w01fe** [comment]
Thanks for the report -- PR welcome, otherwise we'll get to it when we can.
