### ISSUE TITLE
default values for schemas

### ISSUE THREAD

**Issue by instilled** [Prismatic/schema#276]
Something I'm missing from time to time in schema is the ability to provide default values for schemas.
I was wondering what others think about this feature and if this is something that is intended for future releases? 
Thanks, Fabio

**Comment by w01fe** [comment]
There are some relevant discussions on the mailing list, in particular on the first thread: 

https://groups.google.com/forum/#!searchin/prismatic-plumbing/default$20values

If you can provide some more context on why you want to attach default values and where you want them to take effect, that would be helpful.  As of now there aren't any plans to add something related to defaults but if there's a concrete proposal we like that could change.  (And FWIW, most likely you could add defaulting behavior yourself without needing changes to core).

**Comment by instilled** [comment]
Jason, thanks for the reply. I've read through the relevant mailing list threads. There's some interesting information there. Would you prefer taking the discussion to the mailing list or shall we continue to use the issue? If it's the mailing list, feel free to close the issue.

**Comment by w01fe** [comment]
Hi Fabio,

No problem.  Whatever you prefer is fine, so long as we preserve the
context (i.e., link from here to the relevant past discussions).  I have a
slight preference for keeping it on the mailing list for now, just to keep
all the context together.

Thanks, Jason

**Comment by instilled** [comment]
Hi Jason. I've posted my thoughts here: https://groups.google.com/forum/#!msg/prismatic-plumbing/NWUnqbYhfac/F7QjC-9VCAAJ
I'll be closing this issue now. 
Cheers, Fabio
