### ISSUE TITLE
cond-pre doesn't work nicely with very similar schemas

### ISSUE THREAD

**Issue by MeikeMertsch** [Prismatic/schema#279]
I ran into trouble trying to validate schemas that can be of two different types with cond-pre, when those types are pretty similar:

`(s/validate (s/cond-pre Section Fruitbox) random-fruitbox)` doesn't work, while 
`(s/validate (s/cond-pre Fruitbox Section) random-fruitbox)` does in fact work.

In my case, both Fruitbox and Section are nested maps with the same keys on the highest level:

    (def Section
       {:id           s/Str
        :title        s/Str
        :sectionItems [Subsection]})

with Subsection being another kind of nested maps, pretty similar to the Sections.

    (def Fruitbox 
       {:id           s/Str
        :title        s/Str
        :sectionItems [{:type     s/Str
            :fruitbox {:id    (s/eq "fruitbox-id")
                :image s/Str}}]})

(I simplified both definitions a bit so I might have done small errors in writing here, but they do run with a simple validation like `(s/validate Fruitbox random-fruitbox)` and `(s/validate Section random-section)`)

**Comment by MeikeMertsch** [comment]
Urgs, it says so actually in the docs. Never mind. I just don't have a clue how to solve this then.

**Comment by w01fe** [comment]
This is the meaning of `-pre` in `cond-pre` -- it's like `s/conditional`, but guesses the condition for you based on the surface type.  Have a look at `s/if` or `s/conditional`, where you can try to inspect :sectionItems to figure out which you have.  (If you have control of your data model, I would recommend adding a `:type` key to the top-level items to make it easier to see which is whicih).
