### ISSUE TITLE
`optional` doesn't work at the end of a sequence

### ISSUE THREAD

**Issue by mbossenbroek** [Prismatic/schema#289]
This works:

```clj
=> (schema/validate
     [(schema/optional [schema/Keyword] "Optional")
      (schema/either schema/Keyword schema/Symbol)]
     [[:baz] :foo 'bar])
[[:baz] :foo bar]
```

But this doesn't:

```clj
=> (schema/validate
     [(schema/either schema/Keyword schema/Symbol)
      (schema/optional [schema/Keyword] "Optional")]
     [:foo 'bar [:baz]])
RuntimeException Sequence schema [(either Keyword Symbol) #schema.core.One{:schema [Keyword], :optional? true, :name "Optional"}] does not match [one* optional* rest-schema?]  schema.core/parse-sequence-schema (core.clj:761)
```

**Comment by w01fe** [comment]
Sequence schemas must follow the syntax `[one* optional* rest-schema?]`.  This is to allow greedy matching without backtracking.  Otherwise, e.g., with the schema you provide, it's ambiguous whether `'bar` should be validated against the first schema or the second schema.

**Comment by mbossenbroek** [comment]
Could you update the docstring for the relevant operators (`one` & `optional`) to reflect that limitation? It's also very unclear from the error message that it was an issue with the schema construction itself and not what it was validating.

**Comment by w01fe** [comment]
Sure, when we can. PR also very welcome. Thanks.

**Comment by mbossenbroek** [comment]
Thanks! Appreciate it!
