### ISSUE TITLE
Add tests (and therefore example code) for `map-entry`

### ISSUE THREAD

**Issue by roytruelove** [Prismatic/schema#290]
Currently there aren't any in `schema/core_test.cljx`, and I'm looking for ideas on how to use it.

For instance:

```
(def CommonMapEntrySchema
 (map-entry :foo Bool)
 )

(def SchemaForSomeMap
 {
  :something Bool
  CommonMapEntrySchema
  })
```
of course won't compile because there's not an even number of entries.

**Comment by w01fe** [comment]
Map-entry is currently considered an implementation detail. Can you please
elaborate on your use case?  Thanks!

**Comment by roytruelove** [comment]
I've got a map element that will be repeated in many different places in my schema.  For instance, if I'd want to repeat a map entry for`:foo s/Bool` as follows:

```
{:keyA
 {:keyB s/Bool,
  :somePrettyLongName s/Bool,
  :keyC {:keyD s:Bool, :somePrettyLongName s/Bool}},
 :somePrettyLongName s/Bool}
```

`:somePrettyLongName` is in there lots of times; ideally there's be a way to define it up front and reference it throughout my schema.

Thanks

_(disclaimer - this is coming from a clojure noob)_

**Comment by w01fe** [comment]
Gotcha, thanks.  Since Schemas are just maps, I would recommend just using `merge`.  You can `(def foo {:somePrettyLongName s/Bool})` and then just `(merge foo {:keyD s/Bool})`.  Does that make sense?

**Comment by nowprovision** [comment]
To add to what w01fe said, if you have a look at https://github.com/Prismatic/schema/blob/master/src/cljx/schema/core.cljx#L784 enlightenment awaits

**Comment by roytruelove** [comment]
Yes, merge will do the trick, thanks!  @nowprovision Looking forward to the enlightenment, not quite there yet but working on it :)
