### ISSUE TITLE
Add Date (ISO 8601) as new type upstream

### ISSUE THREAD

**Issue by stannie42** [Prismatic/schema#293]
I saw it is possible to define your own schema types (https://github.com/Prismatic/schema/wiki/Defining-New-Schema-Types-1.0).

I need a type that validates a Date formatted ISO 8601, do you think it is possible to add this type upstream instead of creating my own schema type?

Thanks,
Pierre.

**Comment by w01fe** [comment]
Hi Pierre,

It's something we might consider in the future, but I think this is a can of worms we don't want to open at the moment.  (There are so many date formats, you could easily have a library just devoted to date schemas).  

FWIW, without even adding a new schema type you could possibly just do this with a regex schema, e.g. 
```clojure
(def ISO8601 #"(\d{4})-(\d{2})-(\d{2})T(\d{2})\:(\d{2})\:(\d{2})[+-](\d{2})\:(\d{2})")
(s/check ISO8601 "2012-10-06T04:13:00+00:00")
```  

-Jason

**Comment by stannie42** [comment]
Ok, thank you w01fe!
