### ISSUE TITLE
`cond-pre` not working with complex schema

### ISSUE THREAD

**Issue by stathissideris** [Prismatic/schema#295]
I expected the following to match:

```clojure
(s/check [(s/cond-pre
           [(s/one (s/eq :foo) :n1) (s/one (s/eq :op) :n2)]
           [(s/one (s/eq :bar) :n1) (s/one (s/eq :op) :n2)]
           s/Str)]
         [[:bar :op] "t"])
```

But instead I get:

```
[[(named (not (= :foo :bar)) :n1) nil] nil]
```

It seems to work fine with less complex schemas:

```clojure
(s/check [(s/cond-pre s/Num s/Str)] [10 "foo" 20 30 "bar"])
```

**Comment by w01fe** [comment]
Please have a look at the readme.  If the surface structure of the options
are the same, you will have to use s/if or s/conditional with an explicit
predicate.

**Comment by stathissideris** [comment]
Thanks, and apologies, I didn't read the readme closely enough. It seems that the semantics of `either` (externally identical schemas that are all considered for matching) are gone. Is there any way to achieve what `either` used to do before it was deprecated? I have a real use case for this. Is there a way to achieve this while avoiding the opaque error messages of `either`?

**Comment by w01fe** [comment]
No worries.

Nope, there's no direct replacement for `either`.  Its backtracking nature
caused all sorts of trouble in the implementation besides the error
messages, so Schema is now backtrack-free.  Can you elaborate on your use
case?

**Comment by stathissideris** [comment]
OK. So my use case is this: I'm working on an SVG DSL and the transform attribute is compromised of pairs of operations and parameters like so:

```clojure
[[:rotate [10 60 20]]
 [:scale [2]]
 [:scale [2 3]]
 [:skew-x [30]]]
```

The exact content and count of the parameters depends on the operation. I think I could express this using `conditional` where each predicate would check the first element of the vector, and the schema would match the whole vector, but then I would be checking the first element twice. So I suppose it's possible, but it just looked a bit wrong when I attempted it with `conditional`.

**Comment by w01fe** [comment]
Gotcha.  For this sort of purpose, we usually use abstract-map-schema.  The
syntax here is slightly different though (vectors rather than maps), and
you may not need the extensibility part.

I would recommend creating a version of cond-pre for sequence schemas with
a required first element.  It should be a pretty easy modification of
`conditional` or `cond-pre`.  Happy to help if you have questions.
