### ISSUE TITLE
Generating constrained schemas

### ISSUE THREAD

**Issue by atroche** [Prismatic/schema#298]
Hi guys, I'm excited about the new generation and completion features =)

In the README it says “all of the built-in schemas are supported out of the box”, but when I try this:

```clj
(require '[schema.core :as s] '[schema.experimental.generators :as g])
(g/generate (s/constrained Float pos?))
```

I get:

```
java.lang.IllegalArgumentException: No implementation of method: :composite-generator of protocol: #'schema.experimental.generators/CompositeGenerator found for class: schema.spec.variant.VariantSpec
```

And when I do:

```clj
(g/generate s/Int)
```

I get:

```clj
java.lang.IllegalArgumentException: No implementation of method: :composite-generator of protocol: #'schema.experimental.generators/CompositeGenerator found for class: schema.spec.leaf.LeafSpec
```

Is there any easy way to tell which schemas are supported and which aren't?

Thanks!

**Comment by w01fe** [comment]
Those both work fine for me.  

Is it possible you manually recompiled schema.core after loading the generators?  Can you provide a set of commands from fresh repl start and list of dependencies I can use to reproduce this issue?  Thanks.

**Comment by atroche** [comment]
Bah, I can't reproduce it =) Sorry for the hassle.

**Comment by w01fe** [comment]
No worries :)
