### ISSUE TITLE
Can't use Schema 1.0.3 under Clojure 1.7 ?

### ISSUE THREAD

**Issue by dviramontes** [Prismatic/schema#309]
#### 1. what I did:
added the dependency for Schema 1.0.3 to Leiningen dep in project.clj

#### 2. what happened:
ran : `lein run 3000`
and got this stack trace:
```
Exception in thread "main" java.lang.RuntimeException: No such var: s/walker, compiling:(schema_tools/coerce.clj:41:51)
...
Caused by: java.lang.RuntimeException: No such var: s/walker
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
	at clojure.lang.Compiler.resolve(Compiler.java:6963)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
	at clojure.lang.Compiler.analyze(Compiler.java:6506)
	... 176 more
```
#### 3. what i expected to happen:

base on https://github.com/Prismatic/schema#supported-clojure-versions
1.7 should be supported correct ? or am I missing something.

----
#### other things i tried:
running:
```
lein clean 
lein deps
```

running under clojure 1.8.0-rc-2
using schema 1.0.2 , 1.0.1, 1.0.0
but did not help, any ideas would be greatly appreciated ^__^

also my java version is (don't know if this is useful im fairly new to clojure) :
*java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)*

**Comment by w01fe** [comment]
The internals of Schema changed with the 1.0.0 release, and it looks like you're using an older incompatible version of the schema-tools library -- try using at least 0.6.0 it looks like (https://github.com/metosin/schema-tools/blob/master/CHANGES.md)

**Comment by dviramontes** [comment]
@w01fe thanks for the reply.

I guess the other part of the confusion came from not knowing that
both 
`[metosin/schema-tools "0.7.0"]`
and
`[prismatic/schema "1.0.3"]`
libraries were required to use **Schema**

Closing.

**Comment by w01fe** [comment]
Thanks -- FWIW, `schema-tools` is not needed to use schema, it just provides some additional functionality.
