### ISSUE TITLE
constrained predicate gets nil instead of the value

### ISSUE THREAD

**Issue by spacepluk** [Prismatic/schema#313]
When I try `constrained` with a nested schema the predicate gets `nil` instead of the value.  For example:

````clojure
  ;; This works as expected
  (s/validate (s/constrained Str
                             (fn [v] (println "pred " v) true))
              "ASDF")
  ;; prints => "pred ASDF"

  ;; But this doesn't
  (s/validate (s/constrained {:asdf Str}
                             (fn [v] (println "pred " v) true))
              {:asdf "ASDF"})
  ;; prints => "pred nil"
````

**Comment by w01fe** [comment]
Thanks for the report.  What version are you on?  I think this was possibly  [fixed in 1.0.3](https://github.com/Prismatic/schema/blob/master/CHANGELOG.md).

**Comment by spacepluk** [comment]
Hi there, I just checked with 1.0.3 and I get the same behavior.

**Comment by w01fe** [comment]
Just checked and your example works as expected for me with 1.0.3, but not
with 1.0.2.  Can you please check the output of `lein deps :tree` on your
project and make sure you're getting 1.0.3?  And if so, any other info you
can provide about your setup, Clojure(Script) version, etc would be very
helpful.  Thanks!

**Comment by spacepluk** [comment]
You're right, it works with 1.0.3, I must have forgotten to restart the repl or something.  Thanks for you help!

**Comment by w01fe** [comment]
No problem!
