### ISSUE TITLE
Validating against schema from string forces to eval first

### ISSUE THREAD

**Issue by garbanza** [Prismatic/schema#316]
I am sorry if this is not an issue.
Trying to validate json data against edn, so here is the code and output:
```clojure
(schema.core/validate
     (clojure.edn/read-string "{:a schema.core/Int}")
     (clojure.data.json/read-str "{\"a\" : 1}" :key-fn clojure.core/keyword))
IllegalArgumentException No implementation of method: :spec of protocol: #'schema.core/Schema found for class: clojure.lang.Symbol  clojure.core/-cache-protocol-fn (core_deftype.clj:544)
```
However the next works by eval'ing the schema first:
```clojure
(schema.core/validate
     (eval (clojure.edn/read-string "{:a schema.core/Int}"))
     (clojure.data.json/read-str "{\"a\" : 1}" :key-fn clojure.core/keyword))
{:req 1}
```

**Comment by w01fe** [comment]
Have a look at:

`(class (first (vals (clojure.edn/read-string "{:a schema.core/Int}"))))` 

and see that `schema.core/Int` is a symbol, not resolved to anything.  `{:a schema.core/Int}` is a piece of code, not data, and so it needs to be evaluated (like any other code) to behave as you expect -- so if you want the above to work, `eval` as you suggest is the right thing.  That said, there may be better ways to do what you're doing that don't require `eval`, but without more context on the situation it's hard to offer concrete advise.
