### ISSUE TITLE
Adding schema support for upper/lower bounds?

### ISSUE THREAD

**Issue by leeorengel** [Prismatic/schema#323]
I've been playing with the experimental generators features (pretty awesome btw), and came across a situation a few times that seems like it would be really useful. Basically, I want to generate a value that has an upper/lower bound reliably.

Right now I can just create a validator function using constrained. e.g. 

`(def BoundedInt (s/constrained s/Int #(<= 0 % 100)))`

But the problem is if I feed a generator based on this to test.check, it may easily fail with a max tries error since the probability of generating this input is relatively low in many cases (e.g. generating a vector of `BoundedInt`s).

Ideally, some form of lower and upper bound support could be added such that the generator code could leverage test.check's `gen/choose` to reliably generate numbers within the range. I notice gen/choose is used in the case of `enums` but that obviously won't really work well for even remotely big ranges.

Is this something that's been considered or am I missing an easier way to accomplish this?

Thanks

**Comment by w01fe** [comment]
You can use the second argument to pass in custom generators for your schemas, e.g., https://github.com/Prismatic/schema/blob/master/test/clj/schema/experimental/generators_test.clj#L32. 

So if you `def` your constrained schema, you can pass a custom generator based on `gen/choose` for it that will always generate values that match.  

Does this meet your needs?

**Comment by leeorengel** [comment]
Not sure how I missed that! That will do the trick. 
Thanks!

**Comment by w01fe** [comment]
Great!  My pleasure.

**Comment by leeorengel** [comment]
I do have one follow up question, in looking at the docstring on `generator`, it says:

`leaf-generators must return generators for all leaf schemas, and can also return generators for non-leaf schemas to override default generation logic.`

The part I was confused about was the `for all leaf schemas`. Looking at the example, it doesn't seem to pass all the leaf schemas in leaf-generators. Can't `leaf-generators` just be thought of as an optional generator-override hook for any schema? Doesn't the underlying implementation handle providing all the leaf generators?

**Comment by w01fe** [comment]
Yeah, I guess that's a bit confusing.  `leaf-generators` is like you say an optional generator-override hook for any schema -- since the default leaf generators are merged in.  The docstring was just meant to convey that if you use a leaf schema that doesn't have a default, you must pass a generator for it.

**Comment by leeorengel** [comment]
OK -- thanks again for the prompt reply.

**Comment by saulshanabrook** [comment]
@leeorengel I can't quite figure out how you did it. Would it be possible for you to paste your code for the `BoundInt` that works with `generate`?

**Comment by w01fe** [comment]
I think you can just pass `{BoundedInt (gen/choose lower upper)}` as `leaf-generators`.
