### ISSUE TITLE
Missing leaf generator for BigDecimal type

### ISSUE THREAD

**Issue by pdxdan** [Prismatic/schema#324]
Schema supports the validation of a BigDecimal type, but test generation and test completion fail with the following error:
`CompilerException java.lang.RuntimeException: You must provide a leaf generator for schema.spec.leaf.LeafSpec@...`

Here's a simple example that reproduces the error:
```clojure
(ns prismatic-schema-generation.bigdecimal-example
  (:require [schema.core :as s]
            [schema.experimental.complete :as c]))
(def Pants
  {:length         long
   :color          s/Str
   :price          BigDecimal
   })
(s/validate Pants (c/complete {:color "green"} Pants))
```

**Comment by w01fe** [comment]
Thanks for the report.  Schema can validate any Java Class (such as BigDecimal), but BigDecimal isn't considered one of the built-in types, so we don't provide a leaf generator (we can't provide one for every built-in class!).  That said, you just need to pass in your own leaf generator to make it work, e.g.

```clojure
(s/validate Pants (c/complete {:color "green"} Pants {} {BigDecimal (clojure.test.check.generators/fmap #(BigDecimal. (str %)) clojure.test.check.generators/double) }))
```

**Comment by pdxdan** [comment]
Thanks for the quick response w01fe. The solution you provided looks helpful, but could result in a lot of extra test code, so I was wondering what you thought about supporting it directly in the schema library? I'd be happy to try and help and submit a pull request for it, but first want to understand:
1) Do you have any objection to supporting leaf generators in schema for non-built-in types (like BigDecimal), or is it simply a low priority to support them?
2) If you did thing they were a good idea, how would you like to see them implemented? As part of the same collection as the other built-in types in the simple-leaf-generators function? Or some other way?
thanks!

**Comment by w01fe** [comment]
It's our stance that this sort of thing probably belongs in a separate library.  We want Schema to be usable out of the box for the core Clojure(Script) types, but also want to keep the library as small and focused as possible.  This is especially true for generators, given the huge variety of Java Classes out there, and (for many such classes) the variation in possible generators for each type, which is a potentially huge surface area for support and maintenance (and would also require us to take a stance on the "right" default generator for each class, which is often context-dependent)

There are a couple Schema extension libraries linked from the README, which might be a good home -- or perhaps a new library would make sense.  Does that seem reasonable to you?

**Comment by pdxdan** [comment]
That sounds good to me. Thanks for the clarification, and for all the great work on Schema.

**Comment by w01fe** [comment]
Cool, thanks for understanding!
