### ISSUE TITLE
cond-pre with map issue?

### ISSUE THREAD

**Issue by matthewrfellows** [Prismatic/schema#328]
Perhaps I'm not understanding what `cond-pre` should do, but, based on the `cond-pre-test` function, it seems to me that the following should pass validation:

`(s/validate (s/cond-pre {:thing s/Any} s/Any) {})`

but it fails.

**Comment by w01fe** [comment]
This is expected -- does the docstring clarification in #329 answer your question?

**Comment by matthewrfellows** [comment]
Yes, it does, thanks a lot.

**Comment by w01fe** [comment]
Great, thanks!
